#include "charts.h"
#include "rels/include/defines.h"

KEEP_VAR GZChart g_charts[61] = {
    {TREASURE_CHART_1, 0},  {TREASURE_CHART_2, 0},  {TREASURE_CHART_3, 0},  {TREASURE_CHART_4, 0},
    {TREASURE_CHART_5, 0},  {TREASURE_CHART_6, 0},  {TREASURE_CHART_7, 1},  {TREASURE_CHART_8, 1},
    {TREASURE_CHART_9, 1},  {TREASURE_CHART_10, 1}, {TREASURE_CHART_11, 0}, {TREASURE_CHART_12, 0},
    {TREASURE_CHART_13, 1}, {TREASURE_CHART_14, 1}, {TREASURE_CHART_15, 0}, {TREASURE_CHART_16, 0},
    {TREASURE_CHART_17, 1}, {TREASURE_CHART_18, 0}, {TREASURE_CHART_19, 1}, {TREASURE_CHART_20, 0},
    {TREASURE_CHART_21, 1}, {TREASURE_CHART_22, 1}, {TREASURE_CHART_23, 0}, {TREASURE_CHART_24, 0},
    {TREASURE_CHART_25, 1}, {TREASURE_CHART_26, 1}, {TREASURE_CHART_27, 1}, {TREASURE_CHART_28, 0},
    {TREASURE_CHART_29, 0}, {TREASURE_CHART_30, 0}, {TREASURE_CHART_31, 0}, {TREASURE_CHART_32, 1},
    {TREASURE_CHART_33, 0}, {TREASURE_CHART_34, 0}, {TREASURE_CHART_35, 0}, {TREASURE_CHART_36, 1},
    {TREASURE_CHART_37, 1}, {TREASURE_CHART_38, 0}, {TREASURE_CHART_39, 0}, {TREASURE_CHART_40, 0},
    {TREASURE_CHART_41, 1}, {TINGLE_CHART, 1},      {GHOST_SHIP_CHART, 1},  {INCREDIBLE_CHART, 1},
    {BIG_OCTO_CHART, 1},    {FAIRY_CHART, 1},       {HEART_PIECE_CHART, 1}, {SEA_HEARTS_CHART, 1},
    {SECRET_CAVE_CHART, 1}, {LIGHT_RING_CHART, 1},  {PLATFORMS_CHART, 1},   {BEEDLE_CHART, 1},
    {SUBMARINE_CHART, 1},   {TRIFORCE_CHART_1, 0},  {TRIFORCE_CHART_2, 0},  {TRIFORCE_CHART_3, 0},
    {TRIFORCE_CHART_4, 0},  {TRIFORCE_CHART_5, 0},  {TRIFORCE_CHART_6, 0},  {TRIFORCE_CHART_7, 0},
    {TRIFORCE_CHART_8, 0},
};