#pragma once

void SaveMngSpecial_SetLayer0();
void SaveMngSpecial_SetLayer1();
void SaveMngSpecial_SetLayer2();
void SaveMngSpecial_SetLayer3();
void SaveMngSpecial_SetLayer4();
void SaveMngSpecial_SetLayer5();
void SaveMngSpecial_SetLayer8();

void SaveMngSpecial_DTCS();
void SaveMngSpecial_LeafHover();
void SaveMngSpecial_PostLeafHover();
void SaveMngSpecial_ExitThornedFairy();
void SaveMngSpecial_Helmaroc();
void SaveMngSpecial_Hyrule2Skip_AD();
void SaveMngSpecial_BarrierSkip();
void SaveMngSpecial_TrialsSkip();
void SaveMngSpecial_TrialsSkip_AD();
void SaveMngSpecial_PuppetGanon();
void SaveMngSpecial_MorthHover();
void SaveMngSpecial_Ganondorf();

void SaveMngSpecial_BombsSwim_NoMSS();
void SaveMngSpecial_Outside_FH_DC();
void SaveMngSpecial_GanonHover();

void SaveMngSpecial_TrialsSkipAny();
void SaveMngSpecial_LightArrowSkip_Any();
void SaveMngSpecial_PGCutsceneSkip_Any();
void SaveMngSpecial_PGSkip_AD();
void SaveMngSpecial_PGSkip_Any();
void SaveMngSpecial_BarrierSkip_Any();

void SaveMngSpecial_FF1CS_AD();
void SaveMngSpecial_EarlyLeafHover_AD();
void SaveMngSpecial_KalleDemos_AD();
void SaveMngSpecial_DTCS_AD();
void SaveMngSpecial_EnterDRC_AD();
void SaveMngSpecial_DRCMiniboss_AD();
void SaveMngSpecial_DRCBossKeySkip_AD();
void SaveMngSpecial_EnterTOTG_AD();
void SaveMngSpecial_NayrusPearl_AD();
void SaveMngSpecial_TOTG_AD();
void SaveMngSpecial_Darknut_AD();
void SaveMngSpecial_AfterStatue2_AD();
void SaveMngSpecial_HyruleEscape_AD();
void SaveMngSpecial_BarrierSkip_AD();
void SaveMngSpecial_BoomerangSkip_AD();
void SaveMngSpecial_PhantomGanon_AD();
void SaveMngSpecial_EnterHelmaroc_AD();
void SaveMngSpecial_FireMountain_AD();
void SaveMngSpecial_EarlyET_AD();
void SaveMngSpecial_ET_AD();
void SaveMngSpecial_SongstoneSkip_AD();
void SaveMngSpecial_Jalhalla_AD();
void SaveMngSpecial_IceRing_AD();
void SaveMngSpecial_Makar_AD();
void SaveMngSpecial_EnterWT_AD();
void SaveMngSpecial_WT_AD();
void SaveMngSpecial_Wizzrobe_AD();
void SaveMngSpecial_AfterHS_AD();
void SaveMngSpecial_Swim2FCP_AD();