#include "menu.h"

enum Sword {
    NO_SWORD_OWNED = 0,
    HEROS_SWORD_OWNED = 1,
    UNCHARGED_MASTER_SWORD_OWNED = 2,
    HALF_CHARGED_MASTER_SWORD_OWNED = 4,
    FULLY_CHARGED_MASTER_SWORD_OWNED = 8
};

enum Shield {
    NO_SHIELD_OWNED = 0,
    HEROS_SHIELD_OWNED = 1,
    MIRROR_SHIELD_OWNED = 2
};

enum Magic {
    NO_MAGIC = 0,
    SINGLE_MAGIC = 16,
    DOUBLE_MAGIC = 32
};

enum WalletSize {
    WALLET_200 = 0,
    WALLET_1000 = 1,
    WALLET_5000 = 2
};

enum Quiver {
    NO_QUIVER = 0,
    ARROWS_30 = 30,
    ARROWS_60 = 60,
    ARROWS_99 = 99
};

enum BombBag {
    NO_BOMBBAG = 0,
    BOMBS_30 = 30,
    BOMBS_60 = 60,
    BOMBS_99 = 99
};

enum HerosCharm {
    NO_HEROS_CHARM = 0,
    HEROS_CHARM_DISABLED = 1,
    HEROS_CHARM_ENABLED = 2
};

enum Song {
    WINDS_REQUIEM_VALUE = 1,
    BALLAD_OF_GALES_VALUE = 2,
    COMMAND_MELODY_VALUE = 4,
    EARTH_GODS_LYRIC_VALUE = 8,
    WIND_GODS_ARIA_VALUE = 16,
    SONG_OF_PASSING_VALUE = 32
};

enum Pearl {
    NAYRUS_PEARL_VALUE = 1,
    DINS_PEARL_VALUE = 2,
    FARORES_PEARL_VALUE = 4
};

enum TriforcePiece {
    TRIFORCE_PIECE_1_VALUE = 1,
    TRIFORCE_PIECE_2_VALUE = 2,
    TRIFORCE_PIECE_3_VALUE = 4,
    TRIFORCE_PIECE_4_VALUE = 8,
    TRIFORCE_PIECE_5_VALUE = 16,
    TRIFORCE_PIECE_6_VALUE = 32,
    TRIFORCE_PIECE_7_VALUE = 64,
    TRIFORCE_PIECE_8_VALUE = 128
};

enum QuestStatusMenuItems {
    MENU_ITEM_SWORD,
    MENU_ITEM_SHIELD,
    MENU_ITEM_MAGIC,
    MENU_ITEM_WALLET,
    MENU_ITEM_QUIVER,
    MENU_ITEM_HURRICANE_SPIN,
    MENU_ITEM_BOMBAG,
    MENU_ITEM_POWER_BRACELETS,
    MENU_ITEM_PIRATES_CHARM,
    MENU_ITEM_HEROS_CHARM,
    MENU_ITEM_WINDS_REQUIEM,
    MENU_ITEM_BALLAD_OF_GALES,
    MENU_ITEM_COMMAND_MELODY,
    MENU_ITEM_EARTH_GODS_LYRIC,
    MENU_ITEM_WIND_GODS_ARIA,
    MENU_ITEM_SONG_OF_PASSING,
    MENU_ITEM_DINS_PEARL,
    MENU_ITEM_FARORES_PEARL,
    MENU_ITEM_NAYRUS_PEARL,
    MENU_ITEM_TRIFORCE_PIECE_1,
    MENU_ITEM_TRIFORCE_PIECE_2,
    MENU_ITEM_TRIFORCE_PIECE_3,
    MENU_ITEM_TRIFORCE_PIECE_4,
    MENU_ITEM_TRIFORCE_PIECE_5,
    MENU_ITEM_TRIFORCE_PIECE_6,
    MENU_ITEM_TRIFORCE_PIECE_7,
    MENU_ITEM_TRIFORCE_PIECE_8
};

class QuestStatusMenu : public Menu {
public:
    QuestStatusMenu() : Menu() {}
    static void draw();

    static Cursor cursor;
};