#include "menu.h"

enum TreasureChartIndex {
    MENU_TREASURE_CHART_1,
    MENU_TREASURE_CHART_2,
    MENU_TREASURE_CHART_3,
    MENU_TREASURE_CHART_4,
    MENU_TREASURE_CHART_5,
    MENU_TREASURE_CHART_6,
    MENU_TREASURE_CHART_7,
    MENU_TREASURE_CHART_8,
    MENU_TREASURE_CHART_9,
    MENU_TREASURE_CHART_10,
    MENU_TREASURE_CHART_11,
    MENU_TREASURE_CHART_12,
    MENU_TREASURE_CHART_13,
    MENU_TREASURE_CHART_14,
    MENU_TREASURE_CHART_15,
    MENU_TREASURE_CHART_16,
    MENU_TREASURE_CHART_17,
    MENU_TREASURE_CHART_18,
    MENU_TREASURE_CHART_19,
    MENU_TREASURE_CHART_20,
    MENU_TREASURE_CHART_21,
    MENU_TREASURE_CHART_22,
    MENU_TREASURE_CHART_23,
    MENU_TREASURE_CHART_24,
    MENU_TREASURE_CHART_25,
    MENU_TREASURE_CHART_26,
    MENU_TREASURE_CHART_27,
    MENU_TREASURE_CHART_28,
    MENU_TREASURE_CHART_29,
    MENU_TREASURE_CHART_30,
    MENU_TREASURE_CHART_31,
    MENU_TREASURE_CHART_32,
    MENU_TREASURE_CHART_33,
    MENU_TREASURE_CHART_34,
    MENU_TREASURE_CHART_35,
    MENU_TREASURE_CHART_36,
    MENU_TREASURE_CHART_37,
    MENU_TREASURE_CHART_38,
    MENU_TREASURE_CHART_39,
    MENU_TREASURE_CHART_40,
    MENU_TREASURE_CHART_41,
};

class TreasureChartMenu : public Menu {
public:
    TreasureChartMenu() : Menu() {}
    static void draw();

    static Cursor cursor;
};