#pragma once

void SaveMngSpecial_ForestOfFairies_FirstVisit();
void SaveMngSpecial_Ropes1();
void SaveMngSpecial_Ropes2();
void SaveMngSpecial_FF1_PirateShip_Night();
void SaveMngSpecial_Windfall_Day0();
void SaveMngSpecial_DTCS();
void SaveMngSpecial_ExitThornedFairy();
void SaveMngSpecial_HelmarocKing();
void SaveMngSpecial_Hyrule2_BarrierSkip();
void SaveMngSpecial_Hyrule2_BarrierSkip_After();
void SaveMngSpecial_TrialsSkip();
void SaveMngSpecial_TrialsSkip_After();
void SaveMngSpecial_PuppetGanon();
void SaveMngSpecial_PuppetGanon_After();
void SaveMngSpecial_MorthHover_during();
void SaveMngSpecial_MorthHover_after();
void SaveMngSpecial_Ganondorf();
void SaveMngSpecial_Ganondorf_After();
void SaveMngSpecial_LeafHover();
void SaveMngSpecial_LeafHover_After();
void SaveMngSpecial_QuiverAny_After();
void SaveMngSpecial_LightArrowSkip_After();
void SaveMngSpecial_PGCutsceneSkip_After(); 
void SaveMngSpecial_PGSkip(); 
void SaveMngSpecial_PGSkip_After(); 
